/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RepoOwnerNameImport } from './routes/repo/$owner/$name'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RepoOwnerNameRoute = RepoOwnerNameImport.update({
  id: '/repo/$owner/$name',
  path: '/repo/$owner/$name',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/repo/$owner/$name': {
      id: '/repo/$owner/$name'
      path: '/repo/$owner/$name'
      fullPath: '/repo/$owner/$name'
      preLoaderRoute: typeof RepoOwnerNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/repo/$owner/$name': typeof RepoOwnerNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/repo/$owner/$name': typeof RepoOwnerNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/repo/$owner/$name': typeof RepoOwnerNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/repo/$owner/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/repo/$owner/$name'
  id: '__root__' | '/' | '/repo/$owner/$name'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RepoOwnerNameRoute: typeof RepoOwnerNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RepoOwnerNameRoute: RepoOwnerNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/repo/$owner/$name"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/repo/$owner/$name": {
      "filePath": "repo/$owner/$name.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
