/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as AuthIndexImport } from './routes/_auth/index'
import { Route as LoginCallbackImport } from './routes/login/callback'
import { Route as AuthRepoOwnerNameImport } from './routes/_auth/repo/$owner/$name'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const LoginCallbackRoute = LoginCallbackImport.update({
  id: '/login/callback',
  path: '/login/callback',
  getParentRoute: () => rootRoute,
} as any)

const AuthRepoOwnerNameRoute = AuthRepoOwnerNameImport.update({
  id: '/repo/$owner/$name',
  path: '/repo/$owner/$name',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login/callback': {
      id: '/login/callback'
      path: '/login/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof LoginCallbackImport
      parentRoute: typeof rootRoute
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth/repo/$owner/$name': {
      id: '/_auth/repo/$owner/$name'
      path: '/repo/$owner/$name'
      fullPath: '/repo/$owner/$name'
      preLoaderRoute: typeof AuthRepoOwnerNameImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthRepoOwnerNameRoute: typeof AuthRepoOwnerNameRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthRepoOwnerNameRoute: AuthRepoOwnerNameRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthRouteWithChildren
  '/login/callback': typeof LoginCallbackRoute
  '/': typeof AuthIndexRoute
  '/login': typeof LoginIndexRoute
  '/repo/$owner/$name': typeof AuthRepoOwnerNameRoute
}

export interface FileRoutesByTo {
  '/login/callback': typeof LoginCallbackRoute
  '/': typeof AuthIndexRoute
  '/login': typeof LoginIndexRoute
  '/repo/$owner/$name': typeof AuthRepoOwnerNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login/callback': typeof LoginCallbackRoute
  '/_auth/': typeof AuthIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_auth/repo/$owner/$name': typeof AuthRepoOwnerNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/login/callback' | '/' | '/login' | '/repo/$owner/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/login/callback' | '/' | '/login' | '/repo/$owner/$name'
  id:
    | '__root__'
    | '/_auth'
    | '/login/callback'
    | '/_auth/'
    | '/login/'
    | '/_auth/repo/$owner/$name'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginCallbackRoute: typeof LoginCallbackRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginCallbackRoute: LoginCallbackRoute,
  LoginIndexRoute: LoginIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/login/callback",
        "/login/"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/",
        "/_auth/repo/$owner/$name"
      ]
    },
    "/login/callback": {
      "filePath": "login/callback.tsx"
    },
    "/_auth/": {
      "filePath": "_auth/index.tsx",
      "parent": "/_auth"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/_auth/repo/$owner/$name": {
      "filePath": "_auth/repo/$owner/$name.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
